# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
