# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20170618_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cipher',
            field=models.TextField(default='Nonparticipator', max_length=255),
        ),
    ]
