# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='attacker',
            field=models.CharField(default='ROOT', max_length=20),
        ),
        migrations.AddField(
            model_name='attack',
            name='key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attack',
            name='whom',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attack',
            name='atype',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
