# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack', '0002_auto_20170618_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='key',
            field=models.TextField(blank=True, default='NONE'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='result',
            field=models.TextField(blank=True, default='NONE'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='text',
            field=models.TextField(blank=True, default='NONE'),
        ),
    ]
