# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attack', '0003_auto_20170618_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attack',
            old_name='key',
            new_name='akey',
        ),
        migrations.RenameField(
            model_name='attack',
            old_name='result',
            new_name='aresult',
        ),
        migrations.RenameField(
            model_name='attack',
            old_name='text',
            new_name='atext',
        ),
        migrations.RenameField(
            model_name='attack',
            old_name='whom',
            new_name='awhom',
        ),
    ]
