# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack', '0005_auto_20170618_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='output',
            field=models.TextField(blank=True, default='NONE'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='atype',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attack',
            name='result',
            field=models.CharField(default='fail', max_length=20),
        ),
    ]
